version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  test:
    docker:
      - image: 'cimg/base:stable' 
    steps:
      - checkout
      - run: npm install 
      - run: node_modules/.bin/ember test
workflows:
  tests:
    jobs:
      - test
