version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  test:
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: yarn
      - run: node_modules/.bin/ember test
workflows:
  tests:
    jobs:
      - test
